### ISSUE TITLE
hooks not being called

### ISSUE THREAD

**Issue by christf** [24367dfa/ansible-role-dehydrated#11]
hots.sh is set up as per template but never executed.
This seems to be because in the config-file from dehydrated, HOOKS is undefined.

When I define the variable, I can see the hook being executed.

Since these hooks are certificate-specific whiel dehydrated does not support that, there is a need for some  translation mechanism - maybe a script that calls the right hook.sh.

**Comment by penguineer** [comment]
The solution would be to add a file `config` to the cert directory with the content 
```
HOOK=hook.sh
```

**Comment by christf** [comment]
tried it, that works.
